/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAbsenteismoRouteImport } from './routes/_authenticated/absenteismo'
import { Route as AuthenticatedApiRouteImport } from './routes/_authenticated/api'
import { Route as AuthenticatedAtestadosRouteImport } from './routes/_authenticated/atestados'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDesligamentosRouteImport } from './routes/_authenticated/desligamentos'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedInfoSchoolRouteImport } from './routes/_authenticated/info-school'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as ApiPublicRhTabelaRouteImport } from './routes/api/public/rh.$tabela'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbsenteismoRoute =
  AuthenticatedAbsenteismoRouteImport.update({
    id: '/absenteismo',
    path: '/absenteismo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiRoute = AuthenticatedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtestadosRoute = AuthenticatedAtestadosRouteImport.update({
  id: '/atestados',
  path: '/atestados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesligamentosRoute =
  AuthenticatedDesligamentosRouteImport.update({
    id: '/desligamentos',
    path: '/desligamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfoSchoolRoute = AuthenticatedInfoSchoolRouteImport.update({
  id: '/info-school',
  path: '/info-school',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRhTabelaRoute = ApiPublicRhTabelaRouteImport.update({
  id: '/api/public/rh/$tabela',
  path: '/api/public/rh/$tabela',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/absenteismo': typeof AuthenticatedAbsenteismoRoute
  '/api': typeof AuthenticatedApiRoute
  '/atestados': typeof AuthenticatedAtestadosRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desligamentos': typeof AuthenticatedDesligamentosRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/info-school': typeof AuthenticatedInfoSchoolRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/rh/$tabela': typeof ApiPublicRhTabelaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/absenteismo': typeof AuthenticatedAbsenteismoRoute
  '/api': typeof AuthenticatedApiRoute
  '/atestados': typeof AuthenticatedAtestadosRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desligamentos': typeof AuthenticatedDesligamentosRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/info-school': typeof AuthenticatedInfoSchoolRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/rh/$tabela': typeof ApiPublicRhTabelaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/absenteismo': typeof AuthenticatedAbsenteismoRoute
  '/_authenticated/api': typeof AuthenticatedApiRoute
  '/_authenticated/atestados': typeof AuthenticatedAtestadosRoute
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desligamentos': typeof AuthenticatedDesligamentosRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/info-school': typeof AuthenticatedInfoSchoolRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/rh/$tabela': typeof ApiPublicRhTabelaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/absenteismo'
    | '/api'
    | '/atestados'
    | '/avaliacoes'
    | '/cadastros'
    | '/dashboard'
    | '/desligamentos'
    | '/funcionarios'
    | '/info-school'
    | '/usuarios'
    | '/api/public/rh/$tabela'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/absenteismo'
    | '/api'
    | '/atestados'
    | '/avaliacoes'
    | '/cadastros'
    | '/dashboard'
    | '/desligamentos'
    | '/funcionarios'
    | '/info-school'
    | '/usuarios'
    | '/api/public/rh/$tabela'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/absenteismo'
    | '/_authenticated/api'
    | '/_authenticated/atestados'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/cadastros'
    | '/_authenticated/dashboard'
    | '/_authenticated/desligamentos'
    | '/_authenticated/funcionarios'
    | '/_authenticated/info-school'
    | '/_authenticated/usuarios'
    | '/api/public/rh/$tabela'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRhTabelaRoute: typeof ApiPublicRhTabelaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/absenteismo': {
      id: '/_authenticated/absenteismo'
      path: '/absenteismo'
      fullPath: '/absenteismo'
      preLoaderRoute: typeof AuthenticatedAbsenteismoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api': {
      id: '/_authenticated/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AuthenticatedApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atestados': {
      id: '/_authenticated/atestados'
      path: '/atestados'
      fullPath: '/atestados'
      preLoaderRoute: typeof AuthenticatedAtestadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desligamentos': {
      id: '/_authenticated/desligamentos'
      path: '/desligamentos'
      fullPath: '/desligamentos'
      preLoaderRoute: typeof AuthenticatedDesligamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/info-school': {
      id: '/_authenticated/info-school'
      path: '/info-school'
      fullPath: '/info-school'
      preLoaderRoute: typeof AuthenticatedInfoSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/rh/$tabela': {
      id: '/api/public/rh/$tabela'
      path: '/api/public/rh/$tabela'
      fullPath: '/api/public/rh/$tabela'
      preLoaderRoute: typeof ApiPublicRhTabelaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbsenteismoRoute: typeof AuthenticatedAbsenteismoRoute
  AuthenticatedApiRoute: typeof AuthenticatedApiRoute
  AuthenticatedAtestadosRoute: typeof AuthenticatedAtestadosRoute
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesligamentosRoute: typeof AuthenticatedDesligamentosRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedInfoSchoolRoute: typeof AuthenticatedInfoSchoolRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbsenteismoRoute: AuthenticatedAbsenteismoRoute,
  AuthenticatedApiRoute: AuthenticatedApiRoute,
  AuthenticatedAtestadosRoute: AuthenticatedAtestadosRoute,
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesligamentosRoute: AuthenticatedDesligamentosRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedInfoSchoolRoute: AuthenticatedInfoSchoolRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRhTabelaRoute: ApiPublicRhTabelaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
